name: Welcome New Contributor

on:
  pull_request:
    types: [opened]

jobs:
  greet-new-contributor:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is the contributor's first PR
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Hello and welcome! Thank you for your first contribution 🎉
            We appreciate your effort and look forward to more contributions from you!
